# .github/workflows/metrics.yml
name: Metrics
on:
  # Roda a cada 6 horas e também ao fazer push na branch main
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Seu nome de usuário do GitHub
          user: miguel-b-p
          
          # Nome do arquivo de saída
          filename: github-metrics.svg

          # Token do GitHub (necessário)
          token: ${{ secrets.GITHUB_TOKEN }}

          # Configurações para um visual limpo
          config_display: "regular"
          hide_border: yes

          # =========== A MÁGICA ACONTECE AQUI ===========
          # Plugins a serem usados
          base: "header, activity, community, repositories, metadata"
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          
          # CORES EM ESCALA DE CINZA PARA AS LINGUAGENS
          plugin_languages_colors: "gray, #666, #888, #aaa, #ccc, #eee"
          
          # CORES DO TEMA (FUNDO E TEXTO)
          config_colors: "000000, ffffff, ffffff, ffffff, 000000, ffffff"
          # As cores acima são: texto, fundo, borda, anel do gráfico, ícone, linha
