# .github/workflows/metrics.yml
name: Metrics
on:
  # Roda a cada 6 horas e também ao fazer push na branch main
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Seu nome de usuário do GitHub
          user: miguel-b-p
          
          # Nome do arquivo de saída
          filename: github-metrics.svg

          # Token do GitHub (necessário)
          token: ${{ secrets.GITHUB_TOKEN }}

          # ================== A MÁGICA ACONTECE AQUI ==================
          # Removemos a linha "base:" para não mostrar os painéis padrão.
          # Deixamos apenas o plugin de linguagens ativado.
          
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_analysis_timeout: 15
          
          # CORES EM ESCALA DE CINZA PARA AS BARRAS DE LINGUAGENS
          plugin_languages_colors: "gray, #666, #888, #aaa, #ccc, #eee"
          
          # Estilos CSS para manter o tema preto e branco
          extras_css: |
            svg {
              background-color: #ffffff;
            }
            .header, .text, .chart-label, .chart-value, .lines, .legend > g > text {
              fill: #000000 !important;
            }
            .progress-background {
              fill: #dddddd;
            }
